name: Deploy site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# One deployment at a time
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0   # Necessaty for the dates « Last updated »
          lfs: true        # Get content of LFS files

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Zensical
        run: pip install zensical==0.0.63   # current version of zensical (21/09/2026)

      - name: Generate last-updated dates
        run: python scripts/gen_last_updated.py

      - name: Build site
        run: zensical build --clean

      - uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
